# Generated by Django 4.2.6 on 2023-10-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='cta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
