# Generated by Django 4.2.6 on 2023-10-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_hero_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
