# Generated by Django 4.2.6 on 2023-10-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_hero_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image_path',
        ),
    ]
