# Generated by Django 4.2.6 on 2023-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_remove_hero_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('family', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='font_family',
            field=models.ManyToManyField(blank=True, null=True, to='landing.fontfamily'),
        ),
    ]
