# Generated by Django 4.2.6 on 2023-10-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_remove_hero_font_family_hero_general_font_family_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='general_font_family',
            new_name='general_font',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='header_font_family',
            new_name='header_font',
        ),
    ]
