# Generated by Django 4.2.6 on 2023-10-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_rename_name_fontfamily_family_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='general_font_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='sub_title_font_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_font_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
