# Generated by Django 4.2.6 on 2023-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_hero_general_font_size_hero_sub_title_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='title_font_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
